const games = [
  {
    id: 'catan',
    title: 'Catan',
    image: 'immagini/CATAN.jpg',
    description: 'Un classico strategico per costruire insediamenti, raccogliere risorse e dominare la tavola.',
    tag: 'Strategia',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 4,
    link: 'game-details.html?id=catan',
    pdfLink: 'regolamenti/Catan%20ITA.pdf'
  },
  {
    id: 'uno',
    title: 'Uno',
    image: 'immagini/Uno.jpg',
    description: 'Un gioco veloce e divertente da giocare in gruppo, perfetto per riunioni e serate.',
    tag: 'Famiglia',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 10,
    link: 'game-details.html?id=uno',
    pdfLink: 'regolamenti/UNO.pdf'
  },
  {
    id: 'scacchi',
    title: 'Scacchi',
    image: 'immagini/schacchi.jpg',
    description: 'Un classico per mettere alla prova logica, pianificazione e controllo della partita.',
    tag: 'Pensiero',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 2,
    link: 'game-details.html?id=scacchi',
    pdfLink: 'regolamenti/schacchi.pdf'
  },
  {
    id: 'dixit-odyssey',
    title: 'Dixit Odyssey',
    image: 'immagini/Dixit Odyssey.jpg',
    description: 'Un gioco creativo che combina immagini, interpretazione e racconti originali.',
    tag: 'Creatività',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 12,
    link: 'game-details.html?id=dixit-odyssey',
    pdfLink: 'regolamenti/Dixit%20Odyssey.pdf'
  },
  {
    id: 'carcassonne',
    title: 'Carcassonne',
    image: 'immagini/Carcassonne.jpg',
    description: 'Costruisci paesaggi, piazza seguaci e conquista territori in una partita tattica e visiva.',
    tag: 'Tattica',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 5,
    link: 'game-details.html?id=carcassonne',
    pdfLink: 'regolamenti/Carcassonne.pdf'
  },
  {
    id: 'ticket-to-ride',
    title: 'Ticket to Ride',
    image: 'immagini/ticketo to ride.jpg',
    description: 'Collega città e costruisci rotte in questa partita di pianificazione e strategia.',
    tag: 'Percorsi',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 5,
    link: 'game-details.html?id=ticket-to-ride',
    pdfLink: 'regolamenti/ticket%20to%20ride.pdf'
  },
  {
    id: 'mario-kart-8',
    title: 'Mario Kart 8',
    image: 'immagini/Mario kart 8.jpg',
    description: 'Una gara frenetica con kart, item e circuiti famosi, perfetta per sfide veloci e divertenti.',
    tag: 'Corse',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-kart-8'
  },
  {
    id: 'mario-kart-world',
    title: 'Mario Kart World',
    image: 'immagini/Mario kart world.png',
    description: 'Un nuovo capitolo di Mario Kart con percorsi dinamici, velocità elevate e gare da non perdere.',
    tag: 'Corse',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-kart-world'
  },
  {
    id: 'mario-party-jamboree',
    title: 'Mario Party Jamboree',
    image: 'immagini/Mario Party jamboree.png',
    description: 'Una raccolta di minigiochi colorati e frizzanti dove ogni round può cambiare il risultato della partita.',
    tag: 'Party',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-party-jamboree'
  },
  {
    id: 'mario-party',
    title: 'Mario Party',
    image: 'immagini/Mario Party.png',
    description: 'Un classico party game con tabellone, minigiochi e tante strategie per conquistare le stelle.',
    tag: 'Party',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-party'
  },
  {
    id: 'super-smash-bros-ultimate',
    title: 'Super Smash Bros Ultimate',
    image: 'immagini/Super Smash bros ultimate.png',
    description: 'Un picchiaduro accessibile e competitivo, ideale per sfide veloci tra amici e famiglie.',
    tag: 'Picchiaduro',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=super-smash-bros-ultimate'
  },
  {
    id: 'nidhogg',
    title: 'Nidhogg',
    image: 'immagini/Niddhog 2.png',
    description: 'Un duello rapido e intensissimo, dove il movimento, il tempo e l’anticipo fanno la differenza.',
    tag: 'Duello',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 2,
    link: 'game-details.html?id=nidhogg'
  },
  {
    id: 'vagante',
    title: 'Vagante',
    image: 'immagini/Vagante.png',
    description: 'Un gioco di esplorazione e sopravvivenza che mette alla prova resistenza, pianificazione e fortuna.',
    tag: 'Avventura',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=vagante'
  },
  {
    id: 'hidden-in-plain-sight',
    title: 'Hidden in plain sight',
    image: 'immagini/hidden in plain sigth.png',
    description: 'Un gioco di intuizione e osservazione, perfetto per partite leggere e molto coinvolgenti.',
    tag: 'Strategia',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=hidden-in-plain-sight'
  },
  {
    id: 'letal-league-blaze',
    title: 'Letal League Blaze',
    image: 'immagini/Letal League Blaze.jpg',
    description: 'Un videogioco competitivo e rapido, pensato per partite intense e battaglie ad alta velocità.',
    tag: 'Competitivo',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=letal-league-blaze'
  },
  {
    id: 'dany',
    title: 'Dany',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un gioco da tavolo coinvolgente e adatto a gruppi di varie dimensioni.',
    tag: 'Party',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 8,
    link: 'game-details.html?id=dany'
  },
  {
    id: 'risiko-spqr',
    title: 'Risiko S.P.Q.R.',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Conquista territori, pianifica mosse e domina la tavola con strategia e fortuna.',
    tag: 'Strategia',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 5,
    link: 'game-details.html?id=risiko-spqr'
  },
  {
    id: 'cranium',
    title: 'Cranium',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Arte, parole, disegno e pensiero creativo in un gioco dinamico e coinvolgente.',
    tag: 'Creatività',
    category: 'Giochi da tavola',
    minPlayers: 4,
    maxPlayers: 12,
    link: 'game-details.html?id=cranium'
  },
  {
    id: 'exploding-kittens',
    title: 'Explodin Kitten',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Una partita veloce e piena di bluff, azione e reazioni improvvise.',
    tag: 'Party',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 5,
    link: 'game-details.html?id=exploding-kittens'
  },
  {
    id: 'scarabeo',
    title: 'Scarabeo',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un classico del lessico e dell’abilità di combinazione tra parole e punti.',
    tag: 'Parole',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=scarabeo'
  },
  {
    id: 'squillo',
    title: 'Squillo',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un gioco semplice ma sempre divertente da giocare tra amici e familiari.',
    tag: 'Famiglia',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 5,
    link: 'game-details.html?id=squillo'
  },
  {
    id: 'pictonary',
    title: 'Pictonary',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Disegna, indovina e fai ridere il tavolo con un gioco di interpretazione visiva.',
    tag: 'Creatività',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 12,
    link: 'game-details.html?id=pictonary'
  },
  {
    id: 'taboo',
    title: 'Taboo',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Fai descrizioni senza usare parole vietate e prova a far indovinare i compagni.',
    tag: 'Parole',
    category: 'Giochi da tavola',
    minPlayers: 4,
    maxPlayers: 12,
    link: 'game-details.html?id=taboo'
  },
  {
    id: 'ligretto',
    title: 'Ligretto',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un gioco veloce, vivace e perfetto per partite di gruppo ad alta energia.',
    tag: 'Velocità',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 8,
    link: 'game-details.html?id=ligretto'
  },
  {
    id: 'here-to-slay',
    title: 'Here to Slay',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Partita di bluff, battaglie e deduzioni in un gioco molto dinamico.',
    tag: 'Party',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 6,
    link: 'game-details.html?id=here-to-slay'
  },
  {
    id: 'nome-in-codice',
    title: 'Nome in codice',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Svela i codici del tuo team e coordina i messaggi per raggiungere l’obiettivo.',
    tag: 'Team',
    category: 'Giochi da tavola',
    minPlayers: 4,
    maxPlayers: 8,
    link: 'game-details.html?id=nome-in-codice'
  },
  {
    id: 'what-do-you-meme',
    title: 'What do you meme',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un party game con meme, battute e scelte decisamente imprevedibili.',
    tag: 'Humor',
    category: 'Giochi da tavola',
    minPlayers: 4,
    maxPlayers: 10,
    link: 'game-details.html?id=what-do-you-meme'
  },
  {
    id: 'tre-draghi-al-buio',
    title: 'Tre draghi al buio',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un gioco di deduzione e gestione risorse in cui ogni scelta conta.',
    tag: 'Strategia',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 6,
    link: 'game-details.html?id=tre-draghi-al-buio'
  },
  {
    id: 'horse-fever',
    title: 'Horse fever',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Partite rapide e coinvolgenti in cui la fortuna e la gestione del rischio sono decisive.',
    tag: 'Azione',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 6,
    link: 'game-details.html?id=horse-fever'
  },
  {
    id: 'unstable-unicorns',
    title: 'Unstable Unicorns',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Colleziona unicorni, crea combinazioni e cerca di restare in gioco fino alla fine.',
    tag: 'Carte',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 8,
    link: 'game-details.html?id=unstable-unicorns'
  },
  {
    id: 'happy-salmon',
    title: 'Happy Salmon',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un party game veloce e caotico, perfetto per coinvolgere tutto il gruppo.',
    tag: 'Party',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 8,
    link: 'game-details.html?id=happy-salmon'
  },
  {
    id: 'maze-scape',
    title: 'Maze Scape',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un gioco di percorsi e decisioni con un’esplorazione semplice ma tattica.',
    tag: 'Puzzle',
    category: 'Giochi da tavola',
    minPlayers: 1,
    maxPlayers: 1,
    link: 'game-details.html?id=maze-scape'
  },
  {
    id: 'forza-4',
    title: 'Forza 4',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Un classico strategico a turni in cui la pianificazione porta alla vittoria.',
    tag: 'Strategia',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 2,
    link: 'game-details.html?id=forza-4'
  },
  {
    id: 'cluedo',
    title: 'Cluedo',
    image: 'immagini/GameINN Tappetino x5.png',
    description: 'Spia, deduci e risolvi il caso in una partita di logica e osservazione.',
    tag: 'Deduzione',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 6,
    link: 'game-details.html?id=cluedo'
  },
];
