const games = [
  {
    id: 'catan',
    title: 'Catan',
    image: 'immagini/CATAN.jpg',
    description: 'Un classico strategico per costruire insediamenti, raccogliere risorse e dominare la tavola.',
    tag: 'Strategia',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 4,
    link: 'game-details.html?id=catan',
    pdfLink: 'regolamenti/Catan%20ITA.pdf'
  },
  {
    id: 'uno',
    title: 'Uno',
    image: 'immagini/Uno.jpg',
    description: 'Un gioco veloce e divertente da giocare in gruppo, perfetto per riunioni e serate.',
    tag: 'Famiglia',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 10,
    link: 'game-details.html?id=uno',
    pdfLink: 'regolamenti/UNO.pdf'
  },
  {
    id: 'scacchi',
    title: 'Scacchi',
    image: 'immagini/schacchi.jpg',
    description: 'Un classico per mettere alla prova logica, pianificazione e controllo della partita.',
    tag: 'Pensiero',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 2,
    link: 'game-details.html?id=scacchi',
    pdfLink: 'regolamenti/schacchi.pdf'
  },
  {
    id: 'dixit-odyssey',
    title: 'Dixit Odyssey',
    image: 'immagini/Dixit Odyssey.jpg',
    description: 'Un gioco creativo che combina immagini, interpretazione e racconti originali.',
    tag: 'Creatività',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 12,
    link: 'game-details.html?id=dixit-odyssey',
    pdfLink: 'regolamenti/Dixit%20Odyssey.pdf'
  },
  {
    id: 'carcassonne',
    title: 'Carcassonne',
    image: 'immagini/Carcassonne.jpg',
    description: 'Costruisci paesaggi, piazza seguaci e conquista territori in una partita tattica e visiva.',
    tag: 'Tattica',
    category: 'Giochi da tavola',
    minPlayers: 2,
    maxPlayers: 5,
    link: 'game-details.html?id=carcassonne',
    pdfLink: 'regolamenti/Carcassonne.pdf'
  },
  {
    id: 'ticket-to-ride',
    title: 'Ticket to Ride',
    image: 'immagini/ticketo to ride.jpg',
    description: 'Collega città e costruisci rotte in questa partita di pianificazione e strategia.',
    tag: 'Percorsi',
    category: 'Giochi da tavola',
    minPlayers: 3,
    maxPlayers: 5,
    link: 'game-details.html?id=ticket-to-ride',
    pdfLink: 'regolamenti/ticket%20to%20ride.pdf'
  },
  {
    id: 'mario-kart-8',
    title: 'Mario Kart 8',
    image: 'immagini/Mario kart 8.jpg',
    description: 'Una gara frenetica con kart, item e circuiti famosi, perfetta per sfide veloci e divertenti.',
    tag: 'Corse',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-kart-8'
  },
  {
    id: 'mario-kart-world',
    title: 'Mario Kart World',
    image: 'immagini/Mario kart world.png',
    description: 'Un nuovo capitolo di Mario Kart con percorsi dinamici, velocità elevate e gare da non perdere.',
    tag: 'Corse',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-kart-world'
  },
  {
    id: 'mario-party-jamboree',
    title: 'Mario Party Jamboree',
    image: 'immagini/Mario Party jamboree.png',
    description: 'Una raccolta di minigiochi colorati e frizzanti dove ogni round può cambiare il risultato della partita.',
    tag: 'Party',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-party-jamboree'
  },
  {
    id: 'mario-party',
    title: 'Mario Party',
    image: 'immagini/Mario Party.png',
    description: 'Un classico party game con tabellone, minigiochi e tante strategie per conquistare le stelle.',
    tag: 'Party',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=mario-party'
  },
  {
    id: 'super-smash-bros-ultimate',
    title: 'Super Smash Bros Ultimate',
    image: 'immagini/Super Smash bros ultimate.png',
    description: 'Un picchiaduro accessibile e competitivo, ideale per sfide veloci tra amici e famiglie.',
    tag: 'Picchiaduro',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=super-smash-bros-ultimate'
  },
  {
    id: 'nidhogg',
    title: 'Nidhogg',
    image: 'immagini/Niddhog 2.png',
    description: 'Un duello rapido e intensissimo, dove il movimento, il tempo e l’anticipo fanno la differenza.',
    tag: 'Duello',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 2,
    link: 'game-details.html?id=nidhogg'
  },
  {
    id: 'vagante',
    title: 'Vagante',
    image: 'immagini/Vagante.png',
    description: 'Un gioco di esplorazione e sopravvivenza che mette alla prova resistenza, pianificazione e fortuna.',
    tag: 'Avventura',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=vagante'
  },
  {
    id: 'hidden-in-plain-sight',
    title: 'Hidden in plain sight',
    image: 'immagini/hidden in plain sigth.png',
    description: 'Un gioco di intuizione e osservazione, perfetto per partite leggere e molto coinvolgenti.',
    tag: 'Strategia',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=hidden-in-plain-sight'
  },
  {
    id: 'letal-league-blaze',
    title: 'Letal League Blaze',
    image: 'immagini/Letal League Blaze.jpg',
    description: 'Un videogioco competitivo e rapido, pensato per partite intense e battaglie ad alta velocità.',
    tag: 'Competitivo',
    category: 'Videogiochi',
    minPlayers: 2,
    maxPlayers: 4,
    link: 'game-details.html?id=letal-league-blaze'
  }
];
